# Check Arnoldi
I am going to make sure I understand the output from Arnoldi.  I am going to use our stripey PDE matrix with a few extra non-zeros.

In [1]:
using LinearAlgebra, KrylovKit, SparseArrays
n=12000
A=spzeros(n,n);
for i in 2:n
    A[i,i]=-2.0; A[i,i-1]=1.0; A[i-1,i]=1.0
end
A[1,n]=A[n,1]=1.0;A[1,1]=-2.0
A[4,5]=A[4,7]=-5.0
v=rand(n)

k=45;
iterator = ArnoldiIterator(A, v)
factorization = initialize(iterator)
for i in 1:k-1
@time expand!(iterator, factorization)
end


(VInt, H, res, normRes, b) = factorization

V=zeros(n,k); Idk = Matrix(1.0I,k,k)
v=zeros(n)
for i in 1:k
    V[:,i]=KrylovKit.unproject!(v,VInt,Idk[:,i])
end

  0.274621 seconds (316.36 k allocations: 18.179 MiB, 5.86% gc time, 99.21% compilation time)
  0.002547 seconds (3 allocations: 93.922 KiB)
  0.003815 seconds (3 allocations: 94.000 KiB)
  0.004243 seconds (3 allocations: 93.906 KiB)
  0.006097 seconds (3 allocations: 94.156 KiB)
  0.005923 seconds (2 allocations: 93.828 KiB)
  0.008155 seconds (3 allocations: 94.484 KiB)
  0.005908 seconds (3 allocations: 93.969 KiB)
  0.005140 seconds (2 allocations: 93.828 KiB)
  0.005886 seconds (2 allocations: 93.828 KiB)
  0.007776 seconds (3 allocations: 95.156 KiB)
  0.011978 seconds (2 allocations: 93.828 KiB)
  0.011551 seconds (2 allocations: 93.828 KiB)
  0.015782 seconds (2 allocations: 93.828 KiB)
  0.015920 seconds (2 allocations: 93.828 KiB)
  0.014554 seconds (4 allocations: 96.656 KiB)
  0.017946 seconds (2 allocations: 93.828 KiB)
  0.019460 seconds (2 allocations: 93.828 KiB)
  0.019356 seconds (2 allocations: 93.828 KiB)
  0.025615 seconds (2 allocations: 93.828 KiB)
  0.022627 se

# Checking the output!
$\int_0^2$
$\alpha$

In [15]:
Matrix(H)

4×4 Matrix{Float64}:
 -2.04871  -0.0524138   0.300822   0.90302
  3.76537  -1.05181    -0.90396   -0.173873
  0.0       1.28234    -2.00833    0.555896
  0.0       0.0         1.05932   -1.95845

In [11]:
V'*V

4×4 Matrix{Float64}:
  1.0          -3.53436e-17  1.06046e-17  -1.06875e-17
 -3.53436e-17   1.0          2.10773e-17   2.35194e-17
  1.06046e-17   2.10773e-17  1.0           5.17104e-18
 -1.06875e-17   2.35194e-17  5.17104e-18   1.0

In [24]:
norm(A*V-V*H -res*b')

6.980747984124483e-16

In [22]:
res*b'

12×4 Matrix{Float64}:
 -0.0  -0.0  -0.0  -0.136368
 -0.0  -0.0  -0.0  -0.307192
  0.0   0.0   0.0   0.047899
 -0.0  -0.0  -0.0  -0.0547694
  0.0   0.0   0.0   0.198102
 -0.0  -0.0  -0.0  -0.269457
 -0.0  -0.0  -0.0  -0.216468
 -0.0  -0.0  -0.0  -0.0843728
  0.0   0.0   0.0   0.689997
 -0.0  -0.0  -0.0  -0.192998
  0.0   0.0   0.0   0.68098
 -0.0  -0.0  -0.0  -0.0729946

In [90]:
b

4-element KrylovKit.SimpleBasisVector:
 0
 0
 0
 1

In [91]:
res

12-element Vector{Float64}:
 -0.354296553855302
 -0.1949490813758623
 -0.1550573476618112
  0.020192650332838017
  0.3356775245272991
 -0.32414696207481647
 -0.18355859155920165
  0.2137432646217389
  0.17441839886714403
  0.13119479643378384
 -0.01713166884815578
  0.5739445534303531

In [103]:
using Kronecker
kronecker(b',res)

12×4 Kronecker.KroneckerProduct{Float64, Adjoint{Bool, KrylovKit.SimpleBasisVector}, Matrix{Float64}}:
 -0.0  -0.0  -0.0  -0.354297
 -0.0  -0.0  -0.0  -0.194949
 -0.0  -0.0  -0.0  -0.155057
  0.0   0.0   0.0   0.0201927
  0.0   0.0   0.0   0.335678
 -0.0  -0.0  -0.0  -0.324147
 -0.0  -0.0  -0.0  -0.183559
  0.0   0.0   0.0   0.213743
  0.0   0.0   0.0   0.174418
  0.0   0.0   0.0   0.131195
 -0.0  -0.0  -0.0  -0.0171317
  0.0   0.0   0.0   0.573945