# Iterative Solvers and Sparse Matrices

## Making Sparse Matrices

In [66]:
using SparseArrays, LinearAlgebra
m=12
A = spzeros(m,m)
for i in 2:m
    A[i,i]=-2.0; A[i-1,i]=A[i,i-1]=1.0
end
A[1,1]=-2.0
A

12×12 SparseMatrixCSC{Float64, Int64} with 34 stored entries:
 -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
  1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0

## Doing Things with Sparse Matrices

Convert the sparse matrix to a dense matrix if you want to use the familiar fancy linear algebra commands. 
At this point you have lost any and all of the advantages of a sparse matrix

In [67]:
DenseA=Matrix(A)

12×12 Matrix{Float64}:
 -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0

All you can really do with a native sparse matrix is blindingly fast multiplication! There are however quite a lot of things you can do with just multiplication. 

In [74]:
x=rand(m)
for i in 1:123
    x=A*x
    x=x/norm(x)
end
 [x (eigen(Matrix(A)).vectors)[:,1]]

12×2 Matrix{Float64}:
  0.0894609   0.0938673
 -0.174471   -0.182279
  0.250668    0.260098
 -0.313895   -0.322801
  0.360387    0.366744
 -0.387003   -0.389372
  0.391514    0.389372
 -0.372887   -0.366744
  0.331521    0.322801
 -0.269381   -0.260098
  0.189985    0.182279
 -0.0982212  -0.0938673

## Jacobi Iteration
Here is our first Iterative solver.  It is called the Jacobi iteration. 

In [76]:
x=rand(m); b=rand(m)
Aoff=A+2.0*I
for i in 1:1234
    x = -0.5*(b-Aoff*x)
end
[A*x b]

12×2 Matrix{Float64}:
 0.879035    0.879035
 0.478901    0.478901
 0.00512292  0.00512292
 0.611677    0.611677
 0.900986    0.900986
 0.893156    0.893156
 0.274658    0.274658
 0.931816    0.931816
 0.992835    0.992835
 0.721366    0.721366
 0.621596    0.621596
 0.619942    0.619942