# Iterative Solvers and Sparse Matrices

## Making Sparse Matrices

In [30]:
using SparseArrays, LinearAlgebra
m=12
A = spzeros(m,m)
for i in 2:m
    A[i,i]=-2.0; A[i-1,i]=A[i,i-1]=1.0
end
A[1,1]=-2.0
A

12×12 SparseMatrixCSC{Float64, Int64} with 34 stored entries:
 -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
  1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0

## Doing Things with Sparse Matrices

Convert the sparse matrix to a dense matrix if you want to use the familiar fancy linear algebra commands. 
At this point you have lost any and all of the advantages of a sparse matrix

In [32]:
DenseA=Matrix(A)

12×12 Matrix{Float64}:
 -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0

All you can really do with a native sparse matrix is blindingly fast multiplication! There are however quite a lot of things you can do with just multiplication. 

In [62]:
x=rand(m)
for i in 1:123
    x=A*x
    x=x/norm(x)
end
 [x (eigen(Matrix(A)).vectors)[:,1]]

12×2 Matrix{Float64}:
  0.0936544   0.0938673
 -0.181902   -0.182279
  0.259643    0.260098
 -0.322373   -0.322801
  0.36644     0.366744
 -0.389263   -0.389372
  0.389482    0.389372
 -0.367047   -0.366744
  0.323229    0.322801
 -0.260552   -0.260098
  0.182656    0.182279
 -0.0940799  -0.0938673

## Jacobi Iteration
Here is our first Iterative solver.  It is called the Jacobi iteration. 

In [65]:
x=rand(m); b=rand(m)
Aoff=A+2.0*I
for i in 1:123
    x = -0.5*(b-Aoff*x)
end
[A*x b]

12×2 Matrix{Float64}:
 0.389384   0.390487
 0.569494   0.584516
 0.671847   0.674903
 0.590425   0.617026
 0.458458   0.462767
 0.705832   0.737919
 0.0510674  0.0556423
 0.254655   0.284878
 0.895022   0.898815
 0.713043   0.734477
 0.159296   0.161438
 0.737719   0.745455