# Iterative Solvers and Sparse Matrices

## Making Sparse Matrices

In [30]:
using SparseArrays, LinearAlgebra
m=12
A = spzeros(m,m)
for i in 2:m
    A[i,i]=-2.0; A[i-1,i]=A[i,i-1]=1.0
end
A[1,1]=-2.0
A

12×12 SparseMatrixCSC{Float64, Int64} with 34 stored entries:
 -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
  1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅ 
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0

## Doing Things with Sparse Matrices

Convert the sparse matrix to a dense matrix if you want to use the familiar fancy linear algebra commands. 
At this point you have lost any and all of the advantages of a sparse matrix

In [32]:
DenseA=Matrix(A)

12×12 Matrix{Float64}:
 -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0

All you can really do with a native sparse matrix is blindingly fast multiplication! There are however quite a lot of things you can do with just multiplication. 

In [62]:
x=rand(m)
for i in 1:123
    x=A*x
    x=x/norm(x)
end
 [x (eigen(Matrix(A)).vectors)[:,1]]

12×2 Matrix{Float64}:
  0.0936544   0.0938673
 -0.181902   -0.182279
  0.259643    0.260098
 -0.322373   -0.322801
  0.36644     0.366744
 -0.389263   -0.389372
  0.389482    0.389372
 -0.367047   -0.366744
  0.323229    0.322801
 -0.260552   -0.260098
  0.182656    0.182279
 -0.0940799  -0.0938673

## Jacobi Iteration
Here is our first Iterative solver.  It is called the Jacobi iteration. 

In [64]:
x=rand(m); b=rand(m)
Aoff=A+2.0*I
for i in 1:123
    x = -0.5*(b-Aoff*x)
end
[A*x b]

12×2 Matrix{Float64}:
  0.227346     0.232068
  0.488724     0.493219
  0.37553      0.388615
  0.287352     0.295312
  0.531898     0.550347
  0.820642     0.830244
  0.453297     0.472885
  0.132064     0.141108
 -0.000149433  0.0160894
  0.321863     0.328277
  0.569311     0.578481
  0.476427     0.478742