# Test Matrices
It would be nice to be able to make test matrices with *known* spectra so that we would
know how well our algorithms will converge. 

Specifically we would like to make matrices of various sizes with specified *clustered* eigenvalues.

## General Hard Real Clusters

In [7]:
using LinearAlgebra;
(n1,n2,n7)=(3,4,5)
n=n1+n2+n7
X = randn(n,n);
Lambdas = [1.0*ones(n1); 2.0*ones(n2); 7.0*ones(n7)];
A=X*diagm(Lambdas)*inv(X)

12×12 Matrix{Float64}:
  41.1908    25.4228     -57.0058   …  -2.77355   -42.7027   -17.3546
 -48.6986   -33.3808      84.0111       2.26847    63.0059    27.7606
  29.3563    20.7515     -43.4907      -4.11665   -34.5113   -13.9205
  15.0375    10.8639     -26.9078      -0.167718  -18.2191    -8.94847
  -1.26239    0.0171286   -4.05969      2.465      -2.46768   -2.76984
 -43.1916   -31.9769      76.412    …   1.99706    54.818     25.1872
   6.82486    6.70847    -15.0072      -1.65756   -11.6489    -4.86766
  43.7331    31.4375     -73.6316      -2.63073   -55.38     -23.8656
 -13.0521    -9.82499     23.3189       1.97699    18.7798     8.05945
 -36.1333   -26.3259      56.1386      10.5219     43.1512    16.6702
  42.0823    31.9231     -72.9894   …  -4.49766   -48.9861   -22.6002
 -99.8364   -70.6276     160.187       10.0822    121.222     52.2896

## Symmetric Hard Real Clusters

In [1]:
using LinearAlgebra;
(n1,n2,n7)=(3,4,5)
n=n1+n2+n7
Q = qr(randn(n,n)).Q;
Lambdas = [1.0*ones(n1); 2.0*ones(n2); 7.0*ones(n7)];
A=Q*diagm(Lambdas)*Q'

12×12 Matrix{Float64}:
  3.05603    -0.0669122  -1.11048    …   0.278106   -0.11762    0.796008
 -0.0669122   3.98774     0.910679       0.905267    0.364217   0.16879
 -1.11048     0.910679    5.31378        0.0901222   0.352181   0.365568
 -0.925495    0.126408    0.0945181     -0.336196    1.01222    1.23675
  1.00736     0.360628   -1.1274         0.29613     2.06939   -0.112961
 -0.554173    1.20661     0.195573   …   0.452463    0.586789  -0.985611
  0.248229   -0.355737   -0.370693       0.140431   -0.259293   0.256824
  0.623601    1.66658    -0.833527       0.845311   -0.938512   0.184004
 -0.585568   -0.56159    -1.19825       -0.848303   -0.406292  -0.256628
  0.278106    0.905267    0.0901222      2.21072     0.378416   0.0214266
 -0.11762     0.364217    0.352181   …   0.378416    4.2821    -0.360694
  0.796008    0.16879     0.365568       0.0214266  -0.360694   6.23955

## General Soft Real Clusters

In [14]:
using LinearAlgebra, Random, Distributions
Random.seed!(987654321)
(n1,n2,n7)=(3,4,5)
n=n1+n2+n7
X = randn(n,n)
d = Normal(1, 0.0001)
Lambdas = [1.0*rand(d,n1); 2.0*rand(d,n2); 7.0*rand(d,n7)]
A=X*diagm(Lambdas)*inv(X)
eigen(A).values

12-element Vector{Float64}:
 0.9998884368975044
 1.0000151125048702
 1.000149658922654
 1.9998103162829837
 1.9998322470965966
 2.0000357723570907
 2.0002682160685006
 6.998999872900427
 6.999064642745004
 6.999412395569702
 7.000264041692489
 7.000908826447349

## Complex Conjugate Eigenpairs
To make a CC pair (a, b) and (a, -b) use the block 
     a b
    -b a
or as many copies as you want on the diagonal. 

In [5]:
using LinearAlgebra, Random, Distributions
(n1,nBlock,n7)=(3,3,1)
Block = [1.2 3.4;-3.4 1.2]
n=n1+2*nBlock+n7
Q = qr(randn(n,n)).Q;
A = zeros(n,n);
for i in 1:nBlock
    A[2i-1:2i,2i-1:2i]=Block
end
for i in 2*nBlock+1:2*nBlock+n1
    A[i,i]=1.0
end
for i in 2*nBlock+n1+1:n
    A[i,i]=7.0
end
A=Q*A*Q'
eigen(A).values

10-element Vector{ComplexF64}:
 0.9999999999999992 + 0.0im
 0.9999999999999998 + 0.0im
 1.0000000000000007 + 0.0im
 1.1999999999999997 - 3.4000000000000004im
 1.1999999999999997 - 3.399999999999999im
 1.1999999999999997 + 3.399999999999999im
 1.1999999999999997 + 3.4000000000000004im
                1.2 - 3.4000000000000004im
                1.2 + 3.4000000000000004im
 6.9999999999999964 + 0.0im