# Test Matrices
It would be nice to be able to make test matrices with *known* spectra so that we would
know how well our algorithms will converge. 

Specifically we would like to make matrices of various sizes with specified *clustered* eigenvalues.

## General Hard Real Clusters

In [7]:
using LinearAlgebra;
(n1,n2,n7)=(3,4,5)
n=n1+n2+n7
X = randn(n,n);
Lambdas = [1.0*ones(n1); 2.0*ones(n2); 7.0*ones(n7)];
A=X*diagm(Lambdas)*inv(X)

12×12 Matrix{Float64}:
  41.1908    25.4228     -57.0058   …  -2.77355   -42.7027   -17.3546
 -48.6986   -33.3808      84.0111       2.26847    63.0059    27.7606
  29.3563    20.7515     -43.4907      -4.11665   -34.5113   -13.9205
  15.0375    10.8639     -26.9078      -0.167718  -18.2191    -8.94847
  -1.26239    0.0171286   -4.05969      2.465      -2.46768   -2.76984
 -43.1916   -31.9769      76.412    …   1.99706    54.818     25.1872
   6.82486    6.70847    -15.0072      -1.65756   -11.6489    -4.86766
  43.7331    31.4375     -73.6316      -2.63073   -55.38     -23.8656
 -13.0521    -9.82499     23.3189       1.97699    18.7798     8.05945
 -36.1333   -26.3259      56.1386      10.5219     43.1512    16.6702
  42.0823    31.9231     -72.9894   …  -4.49766   -48.9861   -22.6002
 -99.8364   -70.6276     160.187       10.0822    121.222     52.2896

## Symmetric Hard Real Clusters

In [6]:
using LinearAlgebra;
(n1,n2,n7)=(3,4,5)
n=n1+n2+n7
Q = qr(randn(n,n)).Q;
Lambdas = [1.0*ones(n1); 2.0*ones(n2); 7.0*ones(n7)];
A=Q*diagm(Lambdas)*Q'

12×12 Matrix{Float64}:
  2.36327     0.228759  -0.806164   …  -0.825125    0.344257  -0.20235
  0.228759    4.23845    0.21518       -0.172412    0.310035  -0.48282
 -0.806164    0.21518    4.10637        0.759221    1.18037   -0.745494
  0.0442597  -1.01017    0.225364      -0.0460254   0.907965   1.53641
  1.20608    -0.89042   -0.585432      -0.225977    1.47155    0.148607
 -0.288874    1.63096   -0.801211   …  -0.284164    0.839697   0.567472
 -1.25785    -1.60961   -0.0924787      0.457585    0.120271   0.499867
 -0.984405    0.542544   1.35854        0.598197    0.647366   0.436339
  0.278302   -0.468579   0.17178       -0.0751751   0.546423  -1.73226
 -0.825125   -0.172412   0.759221       2.22146     0.302207  -0.189051
  0.344257    0.310035   1.18037    …   0.302207    4.64519   -0.750351
 -0.20235    -0.48282   -0.745494      -0.189051   -0.750351   3.70035

## General Soft Real Clusters

In [18]:
using LinearAlgebra, Random, Distributions
Random.seed!(987654321)
(n1,n2,n7)=(3,4,5)
n=n1+n2+n7
X = randn(n,n)
d = Normal(1, 0.01)
Lambdas = [1.0*rand(d,n1); 2.0*rand(d,n2); 7.0*rand(d,n7)]
A=X*diagm(Lambdas)*inv(X)

12×12 Matrix{Float64}:
  1.98642    0.796161   -0.0282474  …   1.27505   -0.362556    0.499207
 -1.69455    3.10738     0.302603       0.857239  -1.24971     3.91288
  0.872017  -0.0628688   1.01144       -0.597284  -5.94831    -0.721657
  1.69059   -0.0858435  -0.341319       7.20414   -2.77321    -2.1401
 -1.95715   -0.111778   -0.0848746     -2.40398    0.208994    1.47332
 -1.90921    0.938499    0.686032   …   3.1735    -0.841232    3.60879
  1.23096   -0.17172    -1.36953       -1.25775   -0.108356   -1.2427
 -0.764146  -1.84981     0.751763       1.79147    1.25253    -2.19494
 -1.35708   -1.5586      0.744174      -0.924924   0.0718291  -0.770136
  2.65804    1.97954    -0.641526       7.48958   -0.429164   -0.219691
  1.46083    1.00712    -1.28457    …   1.20961    4.92828     0.254968
 -1.01059    3.03397    -0.272629       0.621352  -0.321311    7.09505

## Complex Conjugate Eigenpairs
To make a CC pair (a, b) and (a, -b) use the block 
     a b
    -b a
or as many copies as you want on the diagonal. 

In [34]:
using LinearAlgebra, Random, Distributions
(n1,nBlock,n7)=(3,3,1)
Block = [1.2 3.4;-3.4 1.2]
n=n1+2*nBlock+n7
Q = qr(randn(n,n)).Q;
A = zeros(n,n);
for i in 1:nBlock
    A[2i-1:2i,2i-1:2i]=Block
end
for i in 2*nBlock+1:2*nBlock+n1
    A[i,i]=1.0
end
for i in 2*nBlock+n1+1:n
    A[i,i]=7.0
end
A=Q*A*Q'

10×10 Matrix{Float64}:
  3.30792     0.503864   0.487193  …  -0.558308     2.52175    -0.0116936
 -1.30525     1.23398   -0.277292      0.00381626  -0.759534   -0.0536902
  0.616552    0.176431   1.25219      -1.77058     -0.245075    0.376206
 -0.616232    2.30237   -0.379986      0.993051     0.466201   -1.55668
  0.0232792   1.71107    1.61071      -0.342428    -1.04138     0.180757
 -1.5272      0.72073    0.399364  …   0.575745    -0.030672    2.75164
  1.39418    -0.94509    0.950139     -0.0641761    0.0544401  -1.10642
  0.0448852   0.124427   1.65919       1.11414     -0.966124    0.349154
  1.09976     0.20374    1.00727       0.665473     2.54383    -0.178563
 -1.87638     0.342442  -0.728229     -0.203141    -1.27108     1.55843