# Python Code
Algorithm 

In [2]:
import numpy as np
import scipy.linalg

# define Cholesky Decomposition Algorithm 23.1 T&B 
def Cholesky(A):
    R = np.triu(A)
    m = np.shape(R)[0]
    # Note Zero indexing
    for k in range(0, m):
        for j in range(k + 1, m):
            R[j,j:m] = R[j,j:m]-(R[k,j:m]*np.conjugate(R[k,j])/R[k,k])
        R[k,k:m] = R[k,k:m]/np.sqrt(R[k,k])
    return R

## Testing
For SPD A the output R should be upper triangular and satisfy the decomposition to reasonable accuracy.

In [9]:
# make SPD random matrix
m = 5
A = np.random.rand(m, m); A = np.transpose(A)@A
R = Cholesky(A)
Residual = A-np.transpose(R)@R
print(R)
print(np.linalg.norm(Residual))

[[ 1.07393029  0.92362776  0.93352426  1.07157967  0.94216819]
 [ 0.          0.74196866  0.36942247  0.43097418  0.544755  ]
 [ 0.          0.          0.74141964  0.11564404 -0.34715565]
 [ 0.          0.          0.          0.45361408 -0.07470946]
 [ 0.          0.          0.          0.          0.28803158]]
6.661338147750939e-16
