# Python Code
Algorithm 26.1

In [68]:
import numpy as np
import scipy.linalg

# define Hessenber Decomposition Algorithm 26.1 T&B p198 
def Hessenberg(AIn):
    A = AIn;
    # Note Zero indexing offset throughout
    for k in range(0, m-2):
        x = A[k:m,k-1]
        v = x
        v[0]+=np.sign(x[0])*np.linalg.norm(x) 
        v = v/np.linalg.norm(v)
        A[k:m,k-1:m] -= 2*np.outer(v, v@A[k:m,k-1:m])
        A[0:m,k:m]   -= 2*np.outer(A[0:m,k:m]@v,v)
    return A

## Testing
For square A the output H should be almots upper triangular i.e. upper Hessenberg and have the same eigenvalues to reasonable accuracy.

In [69]:
# make random square matrix
m = 5
A = np.random.rand(m, m)
v= np.random.rand(m)
lambdaV = np.linalg.eig(A);
H = Hessenberg(A)
print(H)
print(np.linalg.eig(A)[0])
print(np.linalg.eig(H)[0])

[[-0.29166464  0.76184706  1.41375121  0.27643298 -0.87944453]
 [ 1.57651768 -1.16919965 -1.21489144 -0.09486449  1.81191738]
 [ 0.60364299 -0.5077866   0.60177731  0.47571419 -0.08076421]
 [ 0.64285758  0.14260391 -0.19630895  0.7079563   0.38620634]
 [ 0.64000492 -0.40455089  0.14551048  0.16134852 -0.48169836]]
[ 1.38778136+0.j          0.36366298+0.40589703j  0.36366298-0.40589703j
 -1.37396818+0.21830621j -1.37396818-0.21830621j]
[ 1.38778136+0.j          0.36366298+0.40589703j  0.36366298-0.40589703j
 -1.37396818+0.21830621j -1.37396818-0.21830621j]
